SELECT  'DROP VIEW "' || TABLE_CATALOG || '"."' || TABLE_SCHEMA || '"."' || TABLE_NAME || '" CASCADE;'
FROM INFORMATION_SCHEMA.TABLES T
WHERE T.TABLE_NAME LIKE 'RAW_%'
AND T.TABLE_SCHEMA = 'SILVER'
AND T.TABLE_TYPE = 'VIEW'


DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_CUSTOMER_CUSTOMER_LOYALTY" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_FRANCHISE" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_COUNTRY" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_ORDER_DETAIL" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_LOCATION" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_ORDER_HEADER" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_TRUCK" CASCADE;
DROP VIEW "TASTY_BYTES_DBT_DB"."SILVER"."RAW_POS_MENU" CASCADE;
DROP TABLE "TASTY_BYTES_DBT_DB"."SILVER"."RAW_ITEM_CAT_COGS" CASCADE;

DROP TABLE "TASTY_BYTES_DBT_DB"."GOLD".CUSTOMER_LOYALTY_METRICS;
DROP TABLE "TASTY_BYTES_DBT_DB"."GOLD".SALES_METRICS_BY_LOCATION;


SELECT *
FROM SILVER.RAW_ITEM_CAT_COGS


ALTER TASK SILVER.RUN_PREPPED_DATA_DBT RESUME;


DESC API INTEGRATION TB_DBT_GIT_API_INTEGRATION;


USE SECONDARY ROLES NONE;

CREATE DBT PROJECT "TASTY_BYTES_DBT_DB"."SILVER"."TEST_SEC_ROLES_OFF_AGAIN" FROM $$snow://workspace/USER$MSTR_USER1.PUBLIC."getting-started-with-dbt-on-snowflake"/versions/live/tasty_bytes_dbt_demo$$;


CREATE OR REPLACE DBT PROJECT TEST_NEW
  FROM '@TASTY_BYTES_DBT_DB.RAW.TASTY_BYTES_REPO_CLONE/branches/main/tasty_bytes_dbt_demo'
  DEFAULT_VERSION = LAST
  COMMENT = 'Created off Github';


CREATE OR REPLACE GIT REPOSITORY TASTY_BYTES_REPO_CLONE
  ORIGIN = 'https://github.com/thatsy407/getting-started-with-dbt-on-snowflake/'
  API_INTEGRATION = TB_DBT_GIT_API_INTEGRATION
  GIT_CREDENTIALS = INTEGRATIONS.TB_DBT_GIT_SECRET
  COMMENT = 'REPO CLONE';


  DROP GIT REPOSITORY TASTY_BYTES_REPO_CLONE

  SHOW GIT REPOSITORIES

  SHOW GIT BRANCHES IN TASTY_BYTES_REPO_CLONE

  