tasty_bytes:
  target: silver
  outputs:
    silver:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: silver
      warehouse: tasty_bytes_dbt_wh
    gold:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: gold
      warehouse: tasty_bytes_dbt_wh
